#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        # Заменили -a на -x
        start-stop-daemon -S -n aesdsocket -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        # Для надежности здесь тоже лучше использовать -x вместо -n
        start-stop-daemon -K -x /usr/bin/aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
